apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  namespace: shop
  labels:
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name : auth-app-container
          image: ghcr.io/dnullp/googole-shop-gf/auth-app:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: /app/config.yml
            subPath: config.yaml 

